### ISSUE TITLE
Remove hyper dep

### ISSUE THREAD

**Issue by joeirimpan** [zerodhatech/kiteconnect-rs#11]
hyper is being used for injecting headers. lets not bloat the lib :) if we can achieve the same thing without it

**Comment by aurabindo** [comment]
Reqwest uses hyper behind the scenes. So is there a benefit. Although hyper needs a version bump. `0.12` is here, which is what request is probably using. Now it looks like `0.11` hyper is used for headers, and `0.12` for request!

**Comment by joeirimpan** [comment]
https://github.com/zerodhatech/kiteconnect-rs/commit/ce557a2d69f2899663ba3727013fbc51e7b9878b
