### ISSUE TITLE
Quote API not sending instruments?

### ISSUE THREAD

**Issue by aurabindo** [zerodhatech/kiteconnect-rs#13]
Quote sends a GET request with parameters: https://docs.rs/kiteconnect/0.2.3/src/kiteconnect/connect.rs.html#603-612

But the internal send_request does not pass the instruments in the data field since its a GET (https://github.com/zerodhatech/kiteconnect-rs/blob/12adebbc97b06f3d929540d8cad475710cb9703d/src/connect.rs#L682) . As far as I understand, instruments needs to be encoded into the request url. Isnt this the correct behavior ? Calling quote with InstrumentID is giving me"
```
{"message": String("At least one instrument in the format `exchange:tradingsymbol` is required."), "status": String("error")}
```

Follow up question: Is this request url valid: `https://api.kite.trade/quote?i=41729"` It does not have at least one instrument in the format specified in the error message, but the documentation is not very clear either.

**Comment by aurabindo** [comment]
That was quick. Thank you!

**Comment by joeirimpan** [comment]
thanks for reporting. i just released a new version on crates
