### ISSUE TITLE
unable to connect KiteConnect API 

### ISSUE THREAD

**Issue by sachinmalee** [zerodhatech/kiteconnect-rs#15]
from kiteconnect import KiteConnect
api_key="cccc"
api_secret="xxxxx"
request_token="uuuuuu"

kite = KiteConnect(api_key,api_secret)
kite.login_url("")
data=kite.generate_session=("cccccccc",api_secret)
print(data)

Error

TypeError                                 Traceback (most recent call last)
<ipython-input-34-93e950368c4f> in <module>
      5 
      6 kite = KiteConnect(api_key,api_secret)
----> 7 kite.login_url("")
      8 data=kite.generate_session=("uuuuu",api_secret)
      9 print(data)

TypeError: login_url() takes 1 positional argument but 2 were given

**Comment by asnimansari** [comment]
@sachinmalee Isn't this in the code in python library
