### ISSUE TITLE
Order Modification API is not working

### ISSUE THREAD

**Issue by asnimansari** [zerodhatech/kiteconnect-rs#17]
Hi, 
It looks like the Order Modification is using a `POST` request instead of `PUT` request ( as mentioned ) in the Kite Doc.

I tried changing the `POST` request to `PUT`, now the API responds success, but the order is not getting modified in Kite. I tried using `cURL`  request, and it worked.

**Comment by joeirimpan** [comment]
@asnimansari Can you send a PR with that fix?

**Comment by asnimansari** [comment]
@joeirimpan https://github.com/zerodhatech/kiteconnect-rs/pull/18

**Comment by joeirimpan** [comment]
Thank you @asnimansari :)
