### ISSUE TITLE
Missing documentation on how to generate access token

### ISSUE THREAD

**Issue by irfn** [zerodhatech/kiteconnect-rs#19]
You get ApiKey and ApiSecret in the    https://developers.kite.trade/apps
There is no mention on how to get "<AccessToken>"

I used the rust example for fetching holdings and realised that following code was required

```
let loginurl = kiteconnect.login_url();
println!("{:?}", loginurl);
//can follow this to get the request token as a callback as defined by callback url
// or copy to first param

//Following sets the "access token" on the kiteconnext
let resp = kiteconnect.generate_session("<obtained on successful login callback>", "<api_secret>");
```

**Comment by joeirimpan** [comment]
@irfn Thank you. Will be adding this to the docs. For extensive docs, you can visit https://kite.trade/docs/connect/v3/. I 'll also update https://docs.rs/kiteconnect.
