### ISSUE TITLE
Refresh Token Docs

### ISSUE THREAD

**Issue by irfn** [zerodhatech/kiteconnect-rs#20]
I see that the response for generate_session resulted in `"refresh_token" => ""` and I see that access token itself is being used in the `renew_access_token` method. 
IMHO either there should be documentation on expiry or the response of generate_session should return the expiration time/valid until etc.

**Comment by joeirimpan** [comment]
https://kite.trade/docs/connect/v3/user/#response-attributes describes the differences between `refresh_token`, `access_token`. The validity of the `access_token` is also mentioned there.
