### ISSUE TITLE
instruments in mod.rs

### ISSUE THREAD

**Issue by stoxalpha** [zerodhatech/kiteconnect-rs#22]
Shouldn't it be: 
url = self.build_url(format!("/instruments/{}", exchange.unwrap()).as_str(), None);

The / seems to missing.

**Comment by joeirimpan** [comment]
thank you for noticing :+1: 

patch: https://github.com/zerodhatech/kiteconnect-rs/commit/9006a560f160ecc5db55fe8f865ae6ff59278d46

**Comment by stoxalpha** [comment]
thanks for the quick fix!
